SECTION TEXT
LOAD N1*ABC
LOAD N1_ABC
LOAD VAR12
LOAD 1_IUIHI
STOP




SECTION DATA
N1*ABC: CONST 44
N1_ABC: SPACE
1_IUIHI: SPACE
AÇSLKDJFAÇLSKDJFÇALSDKJFÇLSDAKJFÇASDLKJFASDÇLFKJASDFERRTRTAEFASDFASDFASDFHGNGORHHOHGKKNWRGN: CONST 45
12VAR: CONST 4
VAR12: SPACE
MINHA VAR: CONST 30